#!/usr/bin/python
if __name__ == '__main__':
  import sys
  import os
  sys.path.insert(0, os.path.abspath('config'))
  import configure
  configure_options = [
    '--with-shared-libraries=1',
    '--download-suitesparse=yes',
    '--PETSC_ARCH=arch-linux2-gcc-real',
    '--PETSC_DIR=/home/spm105/petsc',
    '--with-boost=yes',
    '--with-boost-dir=/usr',
    '--with-hdf5-dir=/usr',
    '--with-mpi-dir=/usr',
    '--with-petsc4py=yes',
    '--with-python=1',
    '--download-petsc4py=yes',
    # '--with-c2html=0',
    # '--download-ptscotch=yes',
    # '--download-scalapack=yes',
    # '--download-metis=yes',
    # '--download-parmetis=yes',
    # '--download-superlu=yes',
    # '--download-mumps=yes',
    # '--download-pastix=yes',
    # '--download-hypre=yes',
    # '--download-exodusii=yes',
    # '--download-netcdf=yes',
    # '--with-clean=yes',
    ]
  configure.petsc_configure(configure_options)
