#!/usr/bin/python
if __name__ == '__main__':
  import sys
  import os
  sys.path.insert(0, os.path.abspath('config'))
  import configure
  configure_options = [
    # '--with-cc=gcc',
    # '--with-clanguage=c',
    # '--with-dynamic-loading=1',
    '--with-shared-libraries=1',
    '--with-python=1',
    '--download-ptscotch=yes',
    '--download-scalapack=yes',
    '--download-metis=yes',
    '--download-parmetis=yes',
    '--download-superlu=yes',
    '--download-mumps=yes',
    '--download-pastix=yes',
    '--download-hypre=yes',
    '--download-suitesparse=yes',
    '--PETSC_ARCH=arch-linux2-gcc-real',
    '--PETSC_DIR=/home/spm105/petsc',
    '--with-boost=1',
    '--with-boost-dir=/usr',
    '--download-exodusii=yes',
    '--download-netcdf=yes',
    '--with-hdf5-dir=/usr',
    '--with-mpi-dir=/usr',
    '--with-c2html=0'
    # '--download-openmpi=yes'
    ]
  configure.petsc_configure(configure_options)
