#!/usr/bin/python
if __name__ == '__main__':
  import sys
  import os
  sys.path.insert(0, os.path.abspath('config'))
  import configure
  configure_options = [
    # '--with-c2html=0',
    '--with-shared-libraries=1',
    '--download-suitesparse=yes',
    '--PETSC_ARCH=arch-linux2-gcc-real',
    '--PETSC_DIR=/home/spm105/petsc',
    '--with-boost=yes',
    '--with-boost-dir=/usr',
    '--with-hdf5-dir=/usr',
    '--with-mpi-dir=/usr',
    '--with-petsc4py=yes',
    '--with-python=1',
    '--download-petsc4py=yes',
    '--with-tags=1',
    ]
  configure.petsc_configure(configure_options)
