#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xautolock -time 30 -locker "sudo pm-suspend" &
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
# dropboxd &
xbindkeys &
xcompmgr -cF &
nm-applet --sm-disable &
udiskie &
# vboxclient-all &

exec $1

# DEFAULT_SESSION=awesome

# case $1 in
# LXDE)
# 	exec startlxde
# 	;;
# qtile)
# 	exec qtile
# 	;;
# xmonad)
# 	exec xmonad
# 	;;
# *)
# 	exec $DEFAULT_SESSION
# 	;;
# esac
#exec awesome
#exec startlxde
# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice
