#! /usr/bin/zsh

alias hdmi='xrandr --output HDMI1 --auto --left-of LVDS'
alias pres='xrandr --fb 1366x768 --output DP2 --mode 1024x768 --panning 1366x0'
alias mon='xrandr --output DP2 --mode 1680x1050 --left-of eDP1
# feh --bg-fill $HOME/.wallpaper/current.jpg'
alias update='yaourt -Syua --noconfirm'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias emd='emacsclient -nc'
alias em='emacs'
alias emc='emacsclient -t'
alias killemnow='emacsclient -e "(kill-emacs)"'
alias killem="emacsclient -e '(client-save-kill-emacs)'"
alias shu='systemctl poweroff'
alias re='sudo reboot'
alias install='yaourt -S'
alias uninstall='yaourt -Rns'
alias search='yaourt -Ss'
alias clean='sudo pacman -Rns $(pkg-list_true_orphans)'
# alias ps='ps -a -c -o pid,command -x'
alias gen_ctags='find . -name "*.[chCH]" -print | etags -'

# grep
grephistory()
{
    grep $1 $HOME/.dotfiles/zsh/history.log
}
alias his='grephistory'

# SHORTCUT START
alias h="cd ~ && ls -a"
alias d="cd ~/Documents && ls -a"
alias D="cd ~/Downloads && ls -a"
alias pp="cd ~/Pictures && ls -a"
alias vv="cd ~/Videos && ls -a"
alias m="cd ~/Music && ls -a"
alias b="cd ~/Books && ls -a"
alias s="cd ~/.dotfiles/ && ls -a"
alias r="cd / && ls -a"
alias cf="cd ~/.config && ls -a"
alias cfz=emacsclient -nc -a \"\" ~/.zshrc"
alias cfe=emacsclient -nc -a \"\" ~/.emacs.d/init.el"
alias cfr=emacsclient -nc -a \"\" ~/.config/ranger/rc.conf"
alias cfq=emacsclient -nc -a \"\" ~/.config/qutebrowser/config.py"
alias cft=emacsclient -nc -a \"\" ~/.tmux.conf/"
alias cfd=emacsclient -nc -a \"\" ~/.Xresources"
# SHORTCUT END
