#! /usr/bin/zsh

## ZSH Environment Variables
## ~/.config/zsh

export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE=~/.dotfiles/zsh/history.log
# export DISPLAY=:0

export SHELL='/bin/zsh'

export ALTERNATE_EDITOR=""
export EDITOR="emacs"

# export PATH="/usr/local/sbin:\
# /usr/local/bin:\
# /usr/bin:\
# /usr/bin/vendor_perl:\
# /usr/bin/core_perl:\
# $HOME/.dotfiles/bin:"

if [ -f /etc/os-release ]; then
    # freedesktop.org and systemd
    . /etc/os-release
    OS=$NAME
    VER=$VERSION_ID
elif type lsb_release >/dev/null 2>&1; then
    # linuxbase.org
    OS=$(lsb_release -si)
    VER=$(lsb_release -sr)
elif [ -f /etc/lsb-release ]; then
    # For some versions of Debian/Ubuntu without lsb_release command
    . /etc/lsb-release
    OS=$DISTRIB_ID
    VER=$DISTRIB_RELEASE
elif [ -f /etc/debian_version ]; then
    # Older Debian/Ubuntu/etc.
    OS=Debian
    VER=$(cat /etc/debian_version)
elif [ -f /etc/SuSe-release ]; then
    # Older SuSE/etc.
    ...
elif [ -f /etc/redhat-release ]; then
    # Older Red Hat, CentOS, etc.
    ...
else
    # Fall back to uname, e.g. "Linux <version>", also works for BSD, etc.
    OS=$(uname -s)
    VER=$(uname -r)
fi

# Less
export LESSOPEN='| /usr/bin/highlight -O ansi %s'
export LESS='-A$-R$-g$-i$-m$-s'

# PETSc
export PETSC_DIR=$HOME/petsc
export PETSC_ARCH=arch-linux2-gcc-real
export PYTHONPATH=$PYTHONPATH:$PETSC_DIR/$PETSC_ARCH/lib
export PYTHON2PATH=$PYTHON2PATH:$PETSC_DIR/$PETSC_ARCH/lib

# Python virtualenv
case $OS in
    "Arch Linux")
        source /usr/bin/virtualenvwrapper.sh
        ;;
    Linux*Mint)
        source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
        ;;
esac
export WORKON_HOME=$HOME/.virtualenvs

# vim: set ft=zsh
